quantum/app/urls.py
from django.urls import path
from .import views
from django.conf.urls import include
from django.contrib import admin


app_name = 'app'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:article_id>/', views.details, name='details'),
    path('<int:article_id>/leave_comment/', views.leave_comment, name='leave_comment'),
    path('test/', views.test, name='test'),
    path('grappelli/', include('grappelli.urls')),  # grappelli URLS
    path('admin/', admin.site.urls),  # admin site
    path('contact', views.contact, name='contact'),
]

quantum/quantum/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

quantum/app/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.


class Student(models.Model):
    """
    Класс со студентами
    """
    user_surname = models.CharField(max_length=50, verbose_name='Surname')
    user_name = models.CharField(max_length=25, verbose_name='Name')
    user_age = models.IntegerField(verbose_name='Age')

    class Meta:
        verbose_name = 'Студент'
        verbose_name_plural = 'Студенты'

    def __str__(self):
        return str(f'{self.user_name} {self.user_surname} {self.user_age}')


class Article(models.Model):
    article_title = models.CharField('название статьи', max_length=250)
    article_text = models.TextField('текст статьи')
    pub_date = models.DateTimeField('дата публикации')


    def __str__(self):
        return self.article_title


class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    author_name = models.CharField('имя автора', max_length=50)
    comment_text=models.CharField('текст комментария', max_length=500)
    comment_pub_date = models.DateTimeField('дата публикации')


    def __str__(self):
        return self.author_name

quantum/app/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.utils import timezone
from django.http import Http404
from datetime import datetime, date, time
from django.urls import reverse
from .models import *


def index(request):
    latest_articles_list = Article.objects.order_by('-pub_date')[:5]
    return render(request, 'app/list.html', {'latest_articles_list': latest_articles_list})
# Create your views here.


def details(request, article_id):
    try:
      a = Article.objects.get(id=article_id)
      total_comment = len(Comment.objects.filter(article_id=article_id))
    except:
      raise Http404("Статьи не найдены")


    latest_comments_list = a.comment_set.order_by('-id')[:10]
    return render(request, 'app/details.html', {'article': a,
                  'latest_comments_list': latest_comments_list, 'total_comment': total_comment})


def leave_comment(request, article_id):
    try:
      a = Article.objects.get(id=article_id)
    except:
      raise Http404("Статья не найдена")


    a.comment_set.create(author_name=request.POST['name'], comment_text=request.POST['text'], comment_pub_date=datetime.now())

    return HttpResponseRedirect(reverse('app:details', args=(a.id,)))


def test(request):
    return HttpResponse("Тестовая Страница должна содержать код для тестирования")


def contact(request):
    return render(request, 'app/menu1.html')

quantum/app/templates/app/details.html
{% extends 'base.html'%}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title> {{article.article_title}} </title>
    </head>
    {% block content %}
    <h2 style="color:red"> {{article.article_title }} </h2>
    <p style="color:blue"> {{article.article_text}}</p>
    <em>{{article.pub_date}}</em>
    <hr>

<h2>Комментарии: всего {{total_comment}}</h2>
<hr>
{% if latest_comments_list %}
{% for c in latest_comments_list %}
<p>
    <strong>{{c.author_name}}</strong>
    Написал
    {{c.comment_pub_date}}
    <p style="color:green"> {{ c.comment_text}}</p>
    <hr>
</p>
{% endfor %}
{% else %}
Комментарии не найдены
{% endif %}
<form action="{% url 'app:leave_comment' article.id %}" method = "POST">
    {% csrf_token %}
    <input type="text" required placeholder="Ваше имя" name="name"><br>
    <textarea name="text" required="" placeholder="Оставьте комментарий" cols="80" rows="10" ></textarea><br>
    <button type="submit">Оставить комментарий</button>
</form>
{%endblock%}
</html>

quantum/app/templates/app/list.html
{% extends 'base.html' %}
{% block title%}Последние статьи{% endblock %}
{% block content%}
 {% if latest_articles_list %}
 {% for a in latest_articles_list %}
 <a href="/{{a.id}}"> {{ a.article_title }} <p></a>
 {% endfor%}
 {% else %}
 Статьи не найдены )=
 {% endif %}
{% endblock%}

quantum/app/templates/app/menu1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} Мой сайт{% endblock %}</title>
</head>
<body>
    {% block content %} If you have any questions feel free to ask me on email: pos5pudge@gmail.com{% endblock %}
</body>
</html>

quantum/app/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title> Статьи блога </title>
    <link rel="stylesheet" type="text/css" href="{% static 'main.css} %"/>
</head>
<body>
    <div id="wrapper">
        <header id="header">
            <div id="logo"> <img src="{% static 'logo.jpg' %}" alt=""/></div>
            <div id="visot"><img src="{%static 'visot.png' %}" width="600" height="200" alt=""/></div>
        </header>
        <aside id="leftsidebar">
            <nav id="nav">
                <ul> {% block sidenav %}
                    <li> <a href="https://www.w3schools.com"> HTML</a> </li>
                    <li> <a href="/contact"> Свяжитесь с нами</a> </li>
                    {% endblock sidenav %}
                </ul>
            </nav>
        </aside>
        <section id="main">
            <h1> Welcome!</h1>
            {% block content %}
                {% if latest_articles_list %}
                    {% for a in latest_articles_list %}
                        <a href="{% url 'app:details' a.id %}">
                            <p> {{a.article_title}}</p></a>
                    {% endfor %}
                {%else%}
                    Статьи не найдены
                {%endif%}
            {%endblock%}
        </section>
        <footer id="footer"> Copyright & copy; 2022 Personal blog Design</footer>
    </div>
</body>
</html>

quantum/app/templates/base2.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
        "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
    <title>Title</title>
</head>
<body>

</body>
</html>